### PR TITLE
Update CMakeLists.txt

### PR DESCRIPTION
**Pull request by tusharathawale**
Updated CMakeLists.txt to resolve build errors on MacBook Pro. Specifically, added vtkm_rendering to target_link_libraries.
Also, fixed data copy line at line 38.

### CODE REVIEW

**Review by kmorel — APPROVED** [review]
+1

**Comment by kmorel** [comment]
Looking at this again, I'm surprised you had to add `vtkm_rendering` to the link libraries for all the executables that are not directly using rendering. This might be an error in VTK-m that is requiring `vtkm_rendering` for code that is not logically using rendering.

**Comment by tusharathawale** [comment]
Hi Ken,

So, I tried building tut_io.cxx without vtkm_rendering, and got a few errors. I have attached the error log. The errors go away if I add vtkm_rendering. I believe that I get a similar error log for other tutorial examples.

[errorLog.txt](https://github.com/uo-cdux/vtk-m-tutorial/files/7652101/errorLog.txt)

-Tushar

**Comment by kmorel** [comment]
Ah. You need to include `vtkm_io`. `vtkm_rendering` is probably indirectly including `vtkm_io` from a dependency, but it's not the "right" library.

Normally I (probably) would not be so picky. But users are going to use this as a template for what they do.

**Comment by tusharathawale** [comment]
Hi Ken,

You are correct! I believe that vtkm_io was getting indirectly included with vtkm_rendering. After linking with vtkm_io, I did not get any linking errors. I have attached the updated CMakeLists.txt.

Thanks,
Tushar

[CMakeLists.txt](https://github.com/uo-cdux/vtk-m-tutorial/files/7654172/CMakeLists.txt)

**Comment by kmorel** [comment]
Cool. Can you update the branch for this PR with your changes?

```sh
git commit -a
git push -f
```

**Comment by tusharathawale** [comment]
I just updated my branch with the second commit. Is it looking okay?

Thanks,
Tushar

**Comment by tusharathawale** [comment]
Thanks Ken!

**Pull request merged**
